# Loading and exploring data with Pandas - Week 1

This week I not only became proficient in basic Pandas operations, but also gained a deeper understanding of the overall process of handling data.

In [5]:
import pandas as pd

I got the data for Student Performance on an Entrance Examination from the kaggle website.

In [6]:
df = pd.read_csv(r"C:\\Users\\62704\\Documents\\GitHub\\intro-to-ds-24-25-Yinshu_Lu\\data\\Student_Performance_on_an_Entrance_Examination.csv")
df

,Gender,Caste,coaching,Class_ten_education,twelve_education,medium,Class_X_Percentage,Class_XII_Percentage,Father_occupation,Mother_occupation,time,Performance
0,male,General,NO,SEBA,AHSEC,ENGLISH,Excellent,Excellent,DOCTOR,OTHERS,ONE,Excellent
1,male,OBC,WA,SEBA,AHSEC,OTHERS,Excellent,Excellent,SCHOOL_TEACHER,HOUSE_WIFE,TWO,Excellent
2,male,OBC,OA,OTHERS,CBSE,ENGLISH,Excellent,Excellent,BUSINESS,HOUSE_WIFE,TWO,Excellent
3,male,General,WA,SEBA,AHSEC,OTHERS,Excellent,Excellent,SCHOOL_TEACHER,SCHOOL_TEACHER,ONE,Excellent
4,male,General,OA,SEBA,CBSE,ENGLISH,Excellent,Excellent,COLLEGE_TEACHER,HOUSE_WIFE,TWO,Excellent
...,...,...,...,...,...,...,...,...,...,...,...,...
661,female,ST,WA,SEBA,AHSEC,ENGLISH,Good,Vg,OTHERS,HOUSE_WIFE,ONE,Average
662,male,ST,WA,SEBA,AHSEC,ENGLISH,Vg,Good,CULTIVATOR,HOUSE_WIFE,THREE,Average
663,male,ST,WA,SEBA,CBSE,ENGLISH,Good,Vg,OTHERS,SCHOOL_TEACHER,TWO,Average
664,male,ST,WA,SEBA,AHSEC,ENGLISH,Good,Good,SCHOOL_TEACHER,HOUSE_WIFE,THREE,Average
665,female,ST,NO,SEBA,CBSE,ENGLISH,Vg,Good,BUSINESS,OTHERS,ONE,Average

### Viewing Data Column Names

Here I checked all the column names in the dataset to find out what variables are included in the data.

In [7]:
df.columns

Index(['Gender', 'Caste', 'coaching', 'Class_ten_education',
       'twelve_education', 'medium', 'Class_X_Percentage',
       'Class_XII_Percentage', 'Father_occupation', 'Mother_occupation',
       'time', 'Performance'],
      dtype='object')

### Data Types

The data type of each column is shown here, which helps us to see and determine whether data type conversion or preprocessing is required.

In [8]:
df.dtypes

Gender                  object
Caste                   object
coaching                object
Class_ten_education     object
twelve_education        object
medium                  object
Class_X_Percentage      object
Class_XII_Percentage    object
Father_occupation       object
Mother_occupation       object
time                    object
Performance             object
dtype: object

### Summary Data

Summary statistics are generated here for all columns, providing basic facts and information about the data.

In [9]:
df.describe(include = "all")

,Gender,Caste,coaching,Class_ten_education,twelve_education,medium,Class_X_Percentage,Class_XII_Percentage,Father_occupation,Mother_occupation,time,Performance
count,666,666,666,666,666,666,666,666,666,666,666,666
unique,2,4,3,3,3,3,4,4,8,9,6,4
top,male,General,WA,SEBA,AHSEC,ENGLISH,Excellent,Excellent,OTHERS,HOUSE_WIFE,TWO,Good
freq,355,329,449,396,368,536,511,398,277,442,368,210

### Selecting Columns

Here I have statistical descriptive information for the ‘Gender’ column, such as count, number of unique values and so on.

In [10]:
df["Gender"].describe()

count      666
unique       2
top       male
freq       355
Name: Gender, dtype: object

### Counting Columns

Here I calculated the number of occurrences of each of the different values of ‘Gender’ and ‘Caste’ in order to have a more intuitive understanding of the distribution of male and female students and the distribution of the number of students with different castes.

In [11]:
df["Gender"].value_counts()

Gender
male      355
female    311
Name: count, dtype: int64

In [12]:
df["Caste"].value_counts()

Caste
General    329
OBC        162
ST         108
SC          67
Name: count, dtype: int64

Here, the variables ‘Gender’ and ‘Caste’ are combined and counted to analyse the cross-distribution between these two factors.

In [13]:
df[["Gender","Caste"]].value_counts()

Gender  Caste
male    General    188
female  General    141
male    OBC         81
female  OBC         81
male    ST          54
female  ST          54
        SC          35
male    SC          32
Name: count, dtype: int64

### Sorting

Here, the top 10 best performing students are sorted according to the ‘Performance’ column, making it easy to quickly identify high scorers.

In [14]:
df.sort_values(by='Performance', ascending=False)[:10]

,Gender,Caste,coaching,Class_ten_education,twelve_education,medium,Class_X_Percentage,Class_XII_Percentage,Father_occupation,Mother_occupation,time,Performance
204,female,OBC,WA,SEBA,AHSEC,ENGLISH,Excellent,Excellent,SCHOOL_TEACHER,OTHERS,THREE,Vg
206,female,General,WA,SEBA,CBSE,ENGLISH,Excellent,Excellent,BUSINESS,HOUSE_WIFE,TWO,Vg
203,male,General,NO,SEBA,AHSEC,ENGLISH,Excellent,Excellent,ENGINEER,SCHOOL_TEACHER,ONE,Vg
202,female,General,NO,SEBA,AHSEC,ENGLISH,Excellent,Excellent,OTHERS,OTHERS,ONE,Vg
201,male,General,WA,CBSE,CBSE,ENGLISH,Excellent,Excellent,OTHERS,OTHERS,TWO,Vg
200,male,General,WA,SEBA,AHSEC,ENGLISH,Excellent,Excellent,BUSINESS,HOUSE_WIFE,TWO,Vg
199,female,General,WA,SEBA,AHSEC,ENGLISH,Vg,Vg,OTHERS,HOUSE_WIFE,TWO,Vg
198,male,OBC,OA,SEBA,CBSE,ENGLISH,Vg,Excellent,BUSINESS,HOUSE_WIFE,TWO,Vg
197,female,General,WA,SEBA,AHSEC,ENGLISH,Excellent,Vg,BUSINESS,SCHOOL_TEACHER,TWO,Vg
196,male,General,WA,CBSE,CBSE,ENGLISH,Excellent,Excellent,OTHERS,SCHOOL_TEACHER,ONE,Vg

### Filtering

Here I've selected all the rows in the coaching column that have a value other than ‘NO’, that is, they will contain ‘yes’, null, or any other value that is not ‘NO’.

In [15]:
#Filtering of students for coaching
coached_students = df[df["coaching"] != "NO"]
coached_students

,Gender,Caste,coaching,Class_ten_education,twelve_education,medium,Class_X_Percentage,Class_XII_Percentage,Father_occupation,Mother_occupation,time,Performance
1,male,OBC,WA,SEBA,AHSEC,OTHERS,Excellent,Excellent,SCHOOL_TEACHER,HOUSE_WIFE,TWO,Excellent
2,male,OBC,OA,OTHERS,CBSE,ENGLISH,Excellent,Excellent,BUSINESS,HOUSE_WIFE,TWO,Excellent
3,male,General,WA,SEBA,AHSEC,OTHERS,Excellent,Excellent,SCHOOL_TEACHER,SCHOOL_TEACHER,ONE,Excellent
4,male,General,OA,SEBA,CBSE,ENGLISH,Excellent,Excellent,COLLEGE_TEACHER,HOUSE_WIFE,TWO,Excellent
5,male,General,WA,CBSE,CBSE,ENGLISH,Excellent,Excellent,COLLEGE_TEACHER,HOUSE_WIFE,TWO,Excellent
...,...,...,...,...,...,...,...,...,...,...,...,...
660,female,ST,WA,SEBA,CBSE,ENGLISH,Good,Vg,DOCTOR,SCHOOL_TEACHER,TWO,Average
661,female,ST,WA,SEBA,AHSEC,ENGLISH,Good,Vg,OTHERS,HOUSE_WIFE,ONE,Average
662,male,ST,WA,SEBA,AHSEC,ENGLISH,Vg,Good,CULTIVATOR,HOUSE_WIFE,THREE,Average
663,male,ST,WA,SEBA,CBSE,ENGLISH,Good,Vg,OTHERS,SCHOOL_TEACHER,TWO,Average
664,male,ST,WA,SEBA,AHSEC,ENGLISH,Good,Good,SCHOOL_TEACHER,HOUSE_WIFE,THREE,Average

### Missing Values

Data integrity and missing data is checked here. Finding empty records in the ‘time’ column helps to identify possible missing issues in the data.

In [16]:
#Divide without NaN by total length revealing which columns have missing values
df.count() / len(df)

Gender                  1.0
Caste                   1.0
coaching                1.0
Class_ten_education     1.0
twelve_education        1.0
medium                  1.0
Class_X_Percentage      1.0
Class_XII_Percentage    1.0
Father_occupation       1.0
Mother_occupation       1.0
time                    1.0
Performance             1.0
dtype: float64

In [17]:
#Look at rows for which BuildingName(s) contains NaN
df[df["time"].isna()]["time"].values

array([], dtype=object)

### Additional Coding Tasks

In [18]:
#Top 10 rows showing gender, caste, performance
df[["Gender", "Caste", "Performance"]].head(10)

   Gender    Caste Performance
0    male  General   Excellent
1    male      OBC   Excellent
2    male      OBC   Excellent
3    male  General   Excellent
4    male  General   Excellent
5    male  General   Excellent
6  female  General   Excellent
7    male      OBC   Excellent
8  female  General   Excellent
9  female  General   Excellent

In [19]:
#Sort by time ascending and show first 5 rows
time = df.sort_values(by="time", ascending=True)
print(time.head(5))

     Gender    Caste coaching Class_ten_education twelve_education    medium  \
347    male      OBC       NO                SEBA            AHSEC    OTHERS
520    male      OBC       NO                SEBA            AHSEC    OTHERS
484  female      OBC       WA                SEBA            AHSEC  ASSAMESE
377  female      OBC       WA                SEBA            AHSEC   ENGLISH
216  female  General       WA                CBSE             CBSE   ENGLISH

    Class_X_Percentage Class_XII_Percentage Father_occupation  \
347               Good              Average    SCHOOL_TEACHER
520                 Vg              Average    SCHOOL_TEACHER
484          Excellent                   Vg          BUSINESS
377                 Vg                 Good          BUSINESS
216          Excellent                   Vg     BANK_OFFICIAL

    Mother_occupation  time Performance
347        HOUSE_WIFE  FIVE        Good
520        HOUSE_WIFE  FOUR     Average
484            OTHERS  FOUR        Good
377        HOUSE_WIFE  FOUR        Good
216     BANK_OFFICIAL  FOUR          Vg

In [20]:
#Counting the number of different categories of Performance
df["Performance"].value_counts()

Performance
Good         210
Vg           198
Average      157
Excellent    101
Name: count, dtype: int64

In [21]:
#Counting the number of missing values
df[["Class_X_Percentage", "Class_XII_Percentage"]].isna().sum()

Class_X_Percentage      0
Class_XII_Percentage    0
dtype: int64

### Reflection

Through learning Pandas I found it very convenient to manipulate data such as statistics, sorting, missing value handling, etc., which is very effective in achieving data analysis goals.